spring:
  application:
    name: prometheus-spring-demo
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://mongodb:27017/test
management:
  endpoints:
    web:
      exposure:
        include: ["prometheus"]