scrape_configs:
  #  - job_name: "prometheus"
  #    static_configs:
  #      - targets: [ "prometheus:9090" ]
  - job_name: "app"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 3s
    static_configs:
      - targets: [ "dummy:8080" ]
        labels:
          application: 'dummy'
  - job_name: "mongodb"
    static_configs:
      - targets: [ "mongodb-exporter:9216" ]